# Generated by Django 5.1.1 on 2024-10-16 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0006_alter_vehicle_image1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reserved_from", models.DateTimeField()),
                ("reserved_until", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("cancelled", "Cancelled")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehicle")),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "payment_method",
                    models.CharField(choices=[("credit_card", "Credit Card"), ("paypal", "PayPal")], max_length=50),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("braintree_transaction_id", models.CharField(blank=True, max_length=255, null=True)),
                ("braintree_status", models.CharField(blank=True, max_length=255, null=True)),
                ("braintree_error_message", models.TextField(blank=True, null=True)),
                (
                    "reservation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reservations.reservation"),
                ),
            ],
        ),
    ]
