# Generated by Django 5.1.1 on 2024-10-16 19:26

import user_accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccountdetails",
            name="drivers_licence",
            field=models.ImageField(blank=True, null=True, upload_to=user_accounts.models.wrapper),
        ),
        migrations.AlterField(
            model_name="useraccountdetails",
            name="identity_card",
            field=models.ImageField(blank=True, null=True, upload_to=user_accounts.models.wrapper),
        ),
        migrations.AlterField(
            model_name="useraccountdetails",
            name="passport",
            field=models.ImageField(blank=True, null=True, upload_to=user_accounts.models.wrapper),
        ),
        migrations.AlterField(
            model_name="useraccountdetails",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=user_accounts.models.wrapper),
        ),
    ]
