# Generated by Django 5.1.1 on 2024-10-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="drivers_licence",
            new_name="drivers_license",
        ),
    ]
