# Generated by Django 5.1.1 on 2024-10-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="role",
        ),
    ]
