# Generated by Django 5.1.1 on 2024-10-17 08:52

import django.db.models.deletion
import utils.image_renamer
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("is_available", models.BooleanField(default=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_per_week", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_per_month", models.DecimalField(decimal_places=2, max_digits=10)),
                ("picture1", models.ImageField(blank=True, null=True, upload_to=utils.image_renamer.wrapper)),
                ("picture2", models.ImageField(blank=True, null=True, upload_to=utils.image_renamer.wrapper)),
                ("picture3", models.ImageField(blank=True, null=True, upload_to=utils.image_renamer.wrapper)),
                ("picture4", models.ImageField(blank=True, null=True, upload_to=utils.image_renamer.wrapper)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleDetails",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mileage", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
                ("is_new", models.BooleanField(default=True)),
                ("is_automatic", models.BooleanField(default=True)),
                ("has_air_conditioning", models.BooleanField(default=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vehicle", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehicle")),
            ],
        ),
    ]
