# Generated by Django 5.1.1 on 2024-10-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_new", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleBrand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weekly_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("monthly_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehicle")),
            ],
        ),
        migrations.CreateModel(
            name="VehicleAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("available_from", models.DateField()),
                ("available_until", models.DateField()),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehicle")),
            ],
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehiclebrand")),
            ],
        ),
        migrations.AddField(
            model_name="vehicle",
            name="model",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehiclemodel"),
        ),
        migrations.CreateModel(
            name="VehicleReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mileage", models.IntegerField()),
                ("condition", models.TextField()),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vehicles.vehicle")),
            ],
        ),
    ]
