# Generated by Django 5.1.1 on 2024-10-17 08:59

import utils.image_renamer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="picture1",
            field=models.ImageField(upload_to=utils.image_renamer.wrapper),
        ),
    ]
