# Generated by Django 5.1.1 on 2024-10-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_alter_pricing_id_alter_vehicle_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricing",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleavailability",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehiclebrand",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehiclereport",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
