# Generated by Django 5.1.1 on 2024-10-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_alter_vehicle_picture1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledetails",
            name="mileage",
            field=models.IntegerField(default=0),
        ),
    ]
