# Generated by Django 5.1.1 on 2024-10-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_alter_vehicledetails_mileage"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
