# Generated by Django 5.1.1 on 2024-10-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_pricing_is_deleted_vehicle_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclebrand",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
