# Generated by Django 5.1.1 on 2024-10-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0005_vehicle_image1_vehicle_image2_vehicle_image3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="image1",
            field=models.ImageField(upload_to="vehicle_images/"),
        ),
    ]
