# Generated by Django 5.1.1 on 2024-10-16 19:26

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0006_alter_vehicle_image1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="image1",
            field=models.ImageField(upload_to=vehicles.models.wrapper),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to=vehicles.models.wrapper),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to=vehicles.models.wrapper),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to=vehicles.models.wrapper),
        ),
    ]
