# Generated by Django 5.1.1 on 2024-10-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0007_alter_vehicle_image1_alter_vehicle_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="available_from",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="available_until",
            field=models.DateField(default=None),
        ),
        migrations.DeleteModel(
            name="VehicleAvailability",
        ),
    ]
